package:
  name: seismic-rna
  version: 0.19.2

source:
  path: ../src

build:
  noarch: python
  number: 0
  script: python -m pip install .

requirements:
  build:
    - git
    - hatchling
  host:
    - python
    - pip
  run:
    - python>=3.10
    - bowtie2>=2.5.1
    - fastqc>=0.12.1
    - rnastructure>=6.3
    - samtools>=1.17

channels:
  - conda-forge
  - bioconda

test:
  imports:
    - seismicrna
