[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "seismic-rna"
version = "1.0.0"
authors = [
    {name="Matty Allan", email="allan.matt.f@gmail.com"},
    {name="Yves Martin", email="yves@martin.yt"},
    {name="Scott Grote"},
    {name="Alberic de Lajarte"},
]
description = "RNA Structure Ensemble Inference via Sequencing, Mutation Identification, and Clustering"
readme = "README.md"
requires-python = "==3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU GPLv3 License",
    "Operating System :: OS Independent",
]

[project.scripts]
srna = "seismic-rna.main:main_cli"

[project.urls]
"Homepage" = "https://github.com/rouskinlab/seismic-rna"
"Bug Tracker" = "https://github.com/rouskinlab/seismic-rna/issues"

