name: Build Wheels

on:
  # Runs on pushes targeting the main branch
  push:
    branches:
      - main
    paths:
      - src/seismicrna/**
      - pyproject.toml
      - environment.yml
      - .github/workflows/install-test.yml
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, macos, windows]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_PLATFORM: ${{ matrix.platform }}
          # Skip versions of Python that SEISMIC-RNA does not support.
          CIBW_SKIP: "cp39-*"
          # Build universal wheels (Indel + ARM) for macOS.
          CIBW_ARCHS_MACOS: universal2


