name: Build and Publish Project on PyPI

on:
  release:
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pypi
  cancel-in-progress: false

jobs:
  build-publish:
    runs-on: ${{ matrix.platform }}
    # This environment is used for publishing on PyPI
    environment: publish-pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python (Linux)
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install pyenv (macOS)
        if: matrix.platform == 'macos-latest'
        run: |
          brew update
          brew install pyenv
          echo 'eval "$(pyenv init --path)"' >> ~/.zshrc
          echo 'eval "$(pyenv init -)"' >> ~/.zshrc
          source ~/.zshrc
          pyenv install 3.10
          pyenv install 3.11
          pyenv install 3.12
          pyenv global 3.10 3.11 3.12

      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels
        run: |
          cibuildwheel --output-dir dist
        env:
          CIBW_PLATFORM: ${{ matrix.platform == 'ubuntu-latest' && 'linux' || matrix.platform == 'macos-latest' && 'macos' }}
      
      - name: Publish on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

