name: Build and Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install SEISMIC-RNA from its GitHub repository
        run: |
          pip install .

      - name: Install dependencies for building the documentation
        run: |
          echo "WORKING DIRECTORY: $PWD"
          echo "CONTENTS"
          ls .
          echo "PARENT CONTENTS"
          ls ..
          pip install -r docs-requirements.txt

      - name: Build documentation
        run: |
          cd src/userdocs
          bash make.sh
          cd ../..

      - name: Deploy documentation
        uses: sphinx-notes/pages@v3
