name: Build documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
          path: requirements.txt

      - name: Install Readthedocs theme
        run: |
          pip install sphinx sphinx_rtd_theme

      - name: Sphinx build
        run: |
          sphinx-build docs/source _build  -d dirbuild -W 
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true


