name: Run tests

on: [push, pull_request, workflow_dispatch]

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dreem
          environment-file: env.yml
          python-version: 3.10
          auto-update-conda: true
          auto-activate-base: false
          channels: bioconda, conda-forge, defaults
        
      - name: Run tests
        run: |
          pytest dreem/test/test_pipeline.py
            


